config:
  model: yolov5l_640px.onnx
  dnn: False
  size: 640 # note only fewer models have dynamic resolution
  threshold: 0.4 # --conf 0.001 --iou 0.65
  iou_threshold: 0.35
  #video: https://youtu.be/jjlBnrzSGjc?t=29
  #video: ./videos/highway.mp4
  labels: "coco"
  #img_folder: ./data/coco128/images/train2017
  img_folder: ./data/images/
  #img_folder: ./data/nanoval2017/images
  #img_folder: ../../datasets/coco/images/val2017
  test: False # coco benchmark
  webcam: False
  show: True
  save: True
